@baseUrl = http://127.0.0.1:8080


GET {{baseUrl}}/api/v1/list HTTP/1.1

###

POST {{baseUrl}}/api/v1/add HTTP/1.1
Content-Type: application/json

{
  "title": "テスト",
  "content": "コンテンツ"
}

###

PUT {{baseUrl}}/api/v1/update HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "title": "リネームテスト",
  "content": "リネームコンテンツ"
}

###

DELETE {{baseUrl}}/api/v1/delete/2 HTTP/1.1
Content-Type: application/json
